kind: Secret
apiVersion: v1
metadata:
 name: secret-file
 namespace: devopsproject  
data:
  MongoDB_URL: bW9uZ29kYjovL3Jvb3Q6YWRtaW5AbW9uZ28tc2VydmljZToyNzAxNy9lbXM/YXV0aFNvdXJjZT1hZG1pbg== #base64
  PORT: MzAwMA==
  JWT_KEY: and0U2VjcmV0S2V5QUFBMzMzMzNAQEAjIyMjIzg4ODk5OTlqamQ=
  CLOUDINARY_NAME: ZHZ5aHB4eXg1
  CLOUDINARY_API_kEY: OTgzNzYzNDM3NTQzMTky
  CLOUDINARY_API_Secret: LVhtSWJxaE9Bcjh5eVR4VnBxYVMzY25FWHlz 
